### ISSUE TITLE
Wrong repo/author link

### ISSUE THREAD

**Issue by DarremMolko** [dracarys18/git_release_tracker#3]
I have noticed for a while now that it gives the wrong repository and author link, as shown in the screenshots below
**Author**
![Screenshot_20220130-135658](https://user-images.githubusercontent.com/70179709/151709548-9b1236bd-0b55-4852-a6bd-88cf6a58c809.jpg)
**Repository**
![IMG_20220130_140617](https://user-images.githubusercontent.com/70179709/151709570-220ad96c-2546-479b-b7cf-deb077ad0c5b.jpg)
The repository is https://github.com/tachiyomiorg/tachiyomi-preview and belongs to tachiyomiorg.

**Comment by dracarys18** [comment]
It is showing the author who made the release which is infact from GitHub CI.

**Comment by DarremMolko** [comment]
> It is showing the author who made the release which is infact from GitHub CI.

That's true but is that the correct behavior? If you try to open whatever of the two links (for example https://github.com/github-actions[bot]/tachiyomi-preview) in the browser you get a "page not found" error. I think it should always take you (at least for the repository link) to the actual repository.

**Comment by dracarys18** [comment]
Fixed in https://github.com/dracarys18/git_release_tracker/commit/5d4384a5bc0ac93ed4d43fb16f44a88c1df3cfc4
